# Generated by Django 5.2.8 on 2025-11-06 01:01

import main_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_zoodisplayanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='availability',
            field=main_app.models.BooleanChoiceField(choices=[(True, 'Available'), (False, 'Not Available')], default=True),
        ),
    ]
