# Generated by Django 5.0.4 on 2025-10-24 23:56

from django.db import migrations



def create_unique_brands(apps, schema_editor):
    ShoeModel = apps.get_model('main_app', 'Shoe')
    UniqueBrandsModel = apps.get_model('main_app', 'UniqueBrands')

    unique_brands= ShoeModel.objects.values_list('brand', flat=True).distinct()
    # for b in unique_brands:  # ['Nike', 'Addidas']
    # brand= UniqueBrandsModel (brand=b)
    # brand.save() # Not optimal, too many requests

    unique_brands_to_create = [UniqueBrandsModel (brand=b) for b in unique_brands]
    UniqueBrandsModel.objects.bulk_create (unique_brands_to_create)

def reverse_unique_brands_data_creation (apps, schema_editor):
    UniqueBrandsModel = apps.get_model('main_app', 'UniqueBrands')
    UniqueBrandsModel.objects.delete() # DELETE FROM unique_brands;

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(code=create_unique_brands, reverse_code=reverse_unique_brands_data_creation)
    ]
