# Generated by Django 5.0.4 on 2025-10-26 13:24

from django.db import migrations


def set_age_group(apps, schema_editor):
    PersonModel = apps.get_model('main_app', 'Person')

    # TODO: research F object and do the update in one query
    for p in PersonModel.objects.all():
        if p.age < 13:
            p.age_group = "Child"
        elif p.age < 18:
            p.age_group = "Teen"
        else:
            p.age_group = "Adult"

        p.save()


def reverse_age_group(apps, schema_editor):
    PersonModel = apps.get_model('main_app', 'Person')
    default_field = PersonModel._meta.get_field('age_group').default

    # TODO: research bulk update
    for p in PersonModel.objects.all():
        p.age_group = default_field
        p.save()



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(
            code=set_age_group,
            reverse_code=reverse_age_group,
        )
    ]