# Generated by Django 5.0.4 on 2025-10-26 13:58


from django.db import migrations


MULTIPLIER: int = 120
PRICE_THRESHOLD: int = 750


def set_price(apps, schema_editor):
    SmartPhoneModel = apps.get_model('main_app', 'Smartphone')

    # TODO: research bulk_update
    for phone in SmartPhoneModel.objects.all():
        phone.price = len(phone.brand) * MULTIPLIER
        phone.save()


def set_category(apps, schema_editor):
    SmartPhoneModel = apps.get_model('main_app', 'Smartphone')

    # TODO: research bulk_update
    for phone in SmartPhoneModel.objects.all():
        if phone.price <= PRICE_THRESHOLD:
            phone.category = "Cheap"
        else:
            phone.category = "Expensive"

        phone.save()


def set_fields(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def reverse_fields(apps, schema_editor):
    SmartPhoneModel = apps.get_model('main_app', 'Smartphone')
    category_default = SmartPhoneModel._meta.get_field('category').default
    price_default = SmartPhoneModel._meta.get_field('price').default

    for phone in SmartPhoneModel.objects.all():
        phone.category = category_default
        phone.price = price_default
        phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(
            code=set_fields,
            reverse_code=reverse_fields,
        )
    ]