# Generated by Django 5.0.4 on 2025-11-04 19:01
import django
from django.db import migrations, models

from datetime import date
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0002_student'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('student',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='main_app.student')),
                ('subject',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='main_app.subject')),
            ],
        ),
        migrations.AlterModelTable(
            name='studentenrollment',
            table='main_app_student_subjects',  # use existing m2m table name
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(
                through='main_app.StudentEnrollment',
                to='main_app.Subject'
            ),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        ),
        # Add the extra fields to StudentEnrollment
        migrations.AddField(
            model_name='studentenrollment',
            name='enrollment_date',
            field=models.DateField(default=date.today),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='grade',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=1,
                choices=[
                    ('A', 'A'),
                    ('B', 'B'),
                    ('C', 'C'),
                    ('D', 'D'),
                    ('F', 'F'),
                ],
            ),
        ),
        # Finally, rename the table back to the default naming convention
        migrations.AlterModelTable(
            name='studentenrollment',
            table=None,
        ),
    ]
