# Generated by Django 5.0.4 on 2025-11-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_studentenrollment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='grade',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
    ]
