# Generated by Django 5.2.8 on 2025-11-20 23:48

import main_app.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='release_year',
            field=models.PositiveIntegerField(validators=[main_app.validators.RangeValidator(max_value=Decimal('2023'), message='The release year must be between 1990 and 2023', min_value=Decimal('1990'))]),
        ),
    ]
