# Generated by Django 5.0.4 on 2025-10-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_weatherforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='humidity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='precipitation',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
